/// 英文文案表：工作台区域。
///
/// key 是中文原文（Workbench/*.swift 与 UI/Workbench*.swift 里 `t(...)` 的实参），value 是对应英文。
/// 加条目就是加一行：`"设置": "Settings",`
/// 查表与回落规则见 `Core/Localization.swift`。
enum WorkbenchStrings {
    static let english: [String: String] = [
        // 工作台首页（WorkbenchHome）
        "开始": "Start",
        "逐段对照读长文、校对别人的译文、追一个词的来历": "Read long texts side by side, proofread a translation, and trace a word's origin",
        "新文稿用": "New documents use",
        "最近文稿": "Recent documents",
        "译文存在本机，重开不再花钱": "Translations stay on this Mac — reopening costs nothing",
        "最近查过的词": "Recently looked up",
        "全部词源": "All etymology",
        "能做的事": "What you can do",
        "通读全文": "Read through",
        "原文和译文一段对一段。机器悄悄漏掉的句子，会在那一段旁边标出来。": "Source and translation side by side, segment by segment. Sentences the machine quietly dropped are flagged beside that segment.",
        "校对译文": "Proofread Translation",
        "放进原文和别人的译文，逐段标出漏译、错译和前后不一的术语，一键采纳改法。": "Drop in a source and someone else's translation. Omissions, mistranslations and inconsistent terms are flagged segment by segment — accept fixes in one click.",
        "词源": "Etymology",
        "一个英文单词从哪来、意思怎么一步步变过来，每一步都有历代原句作证。": "Where an English word came from and how its meaning changed step by step, each step backed by a historical quotation.",
        "粘贴、拖入，或打开一篇长文": "Paste, drop in, or open a long text",
        "论文、合同、小说的一章、Markdown 文档都行。在这一页任何地方按 ⌘V，直接进入逐段对照，不用先点输入框。": "A paper, a contract, a chapter of a novel, a Markdown document — anything. Press ⌘V anywhere on this page to start reading side by side; no need to click a box first.",
        "粘贴": "Paste",
        "打开文件…": "Open File…",
        "手动输入": "Type it in",
        "松手就开始": "Drop to begin",
        "文本、Markdown 文件或拖进来的文字都行": "Text, a Markdown file, or dragged-in words all work",
        "剪贴板里有一篇": "There's a text on the clipboard",
        "剪贴板里是读过的一篇": "It's a text you've read before",
        "剪贴板里是一个词": "It's a word on the clipboard",
        "剪贴板里有文字": "There's text on the clipboard",
        "通读这篇": "Read this through",
        "接着读第 %d 段": "Continue at segment %d",
        "打开": "Open",
        "查它的来历": "Trace its origin",
        "按 ⌘V 或点「粘贴」，直接进入逐段对照。": "Press ⌘V or click Paste to start reading side by side.",
        "系统不让程序自己读剪贴板。在系统设置的隐私与安全性里允许 Lumi 读取剪贴板，这里就会先给你看前几行。": "macOS won't let the app read the clipboard on its own. Allow Lumi to read the clipboard under Privacy & Security in System Settings, and you'll see the first few lines here.",
        "读过的文章会留在这里，连同译文和标出的漏译。下次打开工作台，从上次停下的那一段接着读。": "Articles you've read stay here, with their translations and flagged omissions. Next time, open the workbench and pick up at the segment where you left off.",
        "接着读": "Continue",
        "从最近移除": "Remove from Recents",
        "校对稿": "Proofread",
        "读到第 %d 段": "Read through segment %d",
        "附说明：%@": "Note: %@",
        "%d 处待改": "%d to fix",
        "未校对 · %d 段": "Not proofread · %d segments",
        "已校 %d / %d 段": "Proofread %d / %d segments",
        "校对完 · 无待改": "Proofread · nothing to fix",
        "%d 段疑似漏译": "%d segments may have omissions",
        "%d 段没译成": "%d segments failed to translate",
        "%d 处校对意见": "%d proofreading notes",
        "未翻译 · %d 段": "Not translated · %d segments",
        "已译 %d / %d 段": "Translated %d / %d segments",
        "已译完 · %d 段": "Fully translated · %d segments",
        "今天": "Today",
        "昨天": "Yesterday",
        "%d月%d日": "%d/%d",
        "%d年%d月%d日": "%d/%d/%d",
        "术语不一致": "Inconsistent terms",
        "拉丁语 · 无知的": "Latin · ignorant",
        "中古英语 · 愚蠢的": "Middle English · foolish",
        "今天 · 令人愉快的": "today · pleasant",
        "字": "characters",
        "词": "words",
        "约 %d 段": "about %d segments",

        // 侧栏与导航（WorkbenchShell）
        "工作台": "Workbench",
        "新文稿": "New Document",
        "词源 · %@": "Etymology · %@",
        "设置": "Settings",
        "新建": "New",
        "最近查过": "Recently looked up",
        "大纲": "Outline",
        "待改": "To fix",
        "待查": "To review",
        "第 %d 段": "Segment %d",
        "没译成": "Failed to translate",
        "疑似漏译": "Possible omission",
        "没校对成": "Failed to proofread",
        "本页": "On this page",
        "%@进入英语": "entered English in the %@",
        "讲解": "Narrative",
        "来历": "Origin",
        "%d 步": "%d steps",
        "有民间词源": "Has a folk etymology",
        "词义变迁": "Meaning shifts",
        "义项": "Senses",
        "引文": "Quotations",
        "同根词": "Cognates",
        "%d 段": "%d segments",
        "%d/%d 段": "%d/%d segments",

        // 阅读页工具栏与状态（WorkbenchView）
        "文档说明与术语表": "Document notes and glossary",
        "文档说明：领域、术语、语体": "Document notes: domain, terms, register",
        "重新校对": "Re-proofread",
        "校对": "Proofread",
        "逐段审读译文，并做机检": "Reads the translation segment by segment, plus machine checks",
        "机检：数字、术语表、格式、篇幅": "Machine checks: numbers, glossary, formatting, length",
        "停止": "Stop",
        "重译全文": "Retranslate All",
        "翻译": "Translate",
        "继续": "Continue",
        "复制全部译文（Markdown）": "Copy Full Translation (Markdown)",
        "复制全部译文": "Copy Full Translation",
        "导出译文…": "Export Translation…",
        "复制校对意见": "Copy Proofreading Notes",
        "换一篇…": "Open Another…",
        "翻译进行中，停止后才能换引擎": "Translation in progress — stop before switching engines",
        "尚未启用任何语言模型，请先在设置里开启一个并填好 Key。": "No language model is enabled yet. Enable one in Settings and fill in its key.",
        "%@：读得到标题、术语表和上下段，术语前后一致。需要联网。": "%@: reads the title, glossary and surrounding paragraphs, keeping terms consistent. Requires a network connection.",
        "%d 处待查": "%d to review",
        "跳到下一处要看的段落": "Jump to the next segment that needs a look",
        "无待改": "Nothing to fix",
        "校对完，没有未处理的意见": "Proofread — no notes left to address",
        "已校 %d/%d 段": "Proofread %d/%d segments",
        "全文比对术语…": "Comparing terms across the document…",
        "%d 段 · %@": "%d segments · %@",
        "这是一篇什么文章？术语、语体上有什么要求？术语表每行一条，如 attention = 注意力": "What is this text? Any requirements on terminology or register? Put one glossary term per line, e.g. color = colour",
        "识别到 %d 条术语，校对时逐段核对。": "Found %d glossary terms — checked against every segment during proofreading.",
        "改完之后重新校对才会生效。": "Changes take effect after you re-proofread.",
        "本机只核对术语表；其余说明要联网模型才读得到。": "On-device checking covers the glossary only; the rest is read only by an online model.",
        "改完之后重译才会生效。": "Changes take effect after you retranslate.",
        "本机翻译逐句工作，读不到这些说明——换成联网才会用上。": "On-device translation works sentence by sentence and can't read these notes — switch to Online to use them.",
        "打开设置": "Open Settings",
        "按文章开头自动判断，整篇统一": "Detected from the start of the text, and consistent throughout",

        // 段落行与校对意见卡片（SegmentViews）
        "校对过，没有待改": "Proofread, nothing to fix",
        "原文里没有这一段": "This segment isn't in the source",
        "译文里没有这一段": "This segment isn't in the translation",
        "没有译文": "No translation",
        "重译": "Retranslate",
        "重试": "Retry",
        "编辑这一段译文": "Edit this segment's translation",
        "编辑译文": "Edit Translation",
        "已改": "Edited",
        "这一段的译文改过": "This segment's translation has been edited",
        "审读中…": "Reviewing…",
        "没校对成：%@": "Couldn't proofread: %@",
        "已采纳 · 「%@」→「%@」": "Accepted · “%@” → “%@”",
        "撤销": "Undo",
        "已忽略 %d 条": "%d dismissed",
        "恢复": "Restore",
        "完成": "Done",
        "取消": "Cancel",
        "Esc 取消": "Esc to cancel",
        "复制译文": "Copy Translation",
        "朗读译文": "Speak Translation",
        "编辑译文…": "Edit Translation…",
        "重新校对这一段": "Re-proofread This Segment",
        "用引擎重译这一段": "Retranslate This Segment with the Engine",
        "重译这一段": "Retranslate This Segment",
        "恢复已忽略的意见": "Restore Dismissed Notes",
        "对错了段落？": "Paired with the wrong paragraph?",
        "这里空出一段（译文整体下移）": "Leave a gap here (shift the translation down)",
        "把下一段译文并进来": "Merge the next segment's translation up",
        "建议": "Suggestion",
        "采纳": "Accept",
        "用建议替换译文里的这几个字": "Replace these words in the translation with the suggestion",
        "忽略": "Dismiss",
        "这条不算问题": "This isn't a problem",
        "公式 · 原样保留": "Formula · kept verbatim",
        "代码 · 不翻译": "Code · not translated",
        "%@ · 不翻译": "%@ · not translated",
        "图片": "Image",
        "原样保留": "Kept verbatim",

        // 菜单与文件面板（WorkbenchController）
        "选一个文本文件（.txt、.md）": "Choose a text file (.txt, .md)",
        "关于 Lumi": "About Lumi",
        "设置…": "Settings…",
        "隐藏 Lumi": "Hide Lumi",
        "退出 Lumi": "Quit Lumi",
        "文件": "File",
        "打开…": "Open…",
        "关闭窗口": "Close Window",
        "编辑": "Edit",
        "重做": "Redo",
        "剪切": "Cut",
        "拷贝": "Copy",
        "全选": "Select All",
        "窗口": "Window",
        "最小化": "Minimize",
        "缩放": "Zoom",
        "%@（译文）": "%@ (translation)",

        // 文档模型里的状态与错误（WorkbenchDocument）
        "未命名": "Untitled",
        "# 校对意见：%@": "# Proofreading notes: %@",
        "共 %d 段，%d 处待改。": "%d segments in total, %d to fix.",
        "## 第 %d 段": "## Segment %d",
        " 建议：「%@」": " Suggestion: “%@”",
        "外来译文": "Imported translation",
        "本机": "On-device",
        "联网": "Online",
        "引擎没有返回这一段，可点重试": "The engine returned nothing for this segment — try again",
        "整段没有译文": "The whole segment has no translation",
        "原文里的 %@ 没出现在译文里": "%@ from the source is missing from the translation",
        "译文比预期短 %d%%，可能有整句没译": "Translation is %d%% shorter than expected — a whole sentence may be missing",
        "机检": "Machine check",
        "逐句审读要用语言模型。在设置里开启一个（如 DeepSeek）并填好 Key；现在只做了机检。": "Reading sentence by sentence needs a language model. Enable one in Settings (e.g. DeepSeek) and fill in its key; only machine checks ran this time.",
        "当前离线，只做了机检。联网后再点校对。": "Offline — only machine checks ran. Reconnect and proofread again.",
        "模型没有返回这一段，可点重试": "The model returned nothing for this segment — try again",
        "术语表要求把 %@ 译作「%@」": "The glossary says to render %@ as “%@”",
        "%@ 在%@译作「%@」，这里是「%@」": "In %2$@, %1$@ is rendered “%3$@”, but here it's “%4$@”",

        // 校对意见类型名与说明（Proofreading）
        "漏译": "Omission",
        "增译": "Addition",
        "错译": "Mistranslation",
        "术语": "Terminology",
        "数字": "Number",
        "语病": "Grammar",
        "措辞": "Wording",
        "格式": "Format",
        "全文比对": "Document-wide",
        "原文里没有对应的段落，译文多出了这一段": "There's no matching paragraph in the source; the translation adds this one",
        "这一段在译文里找不到对应": "This paragraph has no counterpart in the translation",
        "这一段看起来没有翻译，仍是%@": "This paragraph doesn't look translated — it's still %@",
        "行内代码 `%@` 应原样保留，译文里没有": "Inline code `%@` should be kept verbatim but is missing from the translation",
        "链接地址 %@ 在译文里丢了": "The link %@ is missing from the translation",
        "术语表要求把 %@ 译作「%@」，这一段没有用": "The glossary says to render %@ as “%@”, but this paragraph didn't",
        "已取消": "Canceled",
        "模型的回答读不懂，可重试": "Couldn't parse the model's answer — try again",

        // 本机引擎（OfflineWorkbenchEngine）
        "本机翻译": "On-device translation",
        "离线可用。逐句翻译，读不到上下文与术语表。": "Works offline. Translates sentence by sentence and can't read context or a glossary.",
        "语言未指定": "Language not specified",
        "需先在「系统设置 › 通用 › 语言与地区 › 翻译语言」下载语言包": "First download the language pack in System Settings › General › Language & Region › Translation Languages",
        "系统翻译不支持 %@ → %@": "System translation doesn't support %@ → %@",
        "未知状态": "Unknown state",
        "不支持的语言": "Unsupported language",
        "本机翻译未返回结果": "On-device translation returned no result",

        // 联网引擎（OnlineWorkbenchEngine）
        "联网模型": "Online model",
        "读得到标题、术语表和上下段，术语前后一致。需要联网。": "Reads the title, glossary and surrounding paragraphs, keeping terms consistent. Requires a network connection.",
        "还没有启用语言模型。在设置里开启一个（如 DeepSeek）并填好 API Key，或改用本机翻译。": "No language model is enabled yet. Enable one in Settings (e.g. DeepSeek) and fill in its API key, or switch to on-device translation.",
        "当前离线": "Offline",
        "未配置语言模型": "No language model configured",
    ]
}
